=pod

=head1 NAME

Net::BitTorrent::Todo - TODO list for Perl module Net::BitTorrent

=head1 High priorities

=over

=item * documentation and safety checks for newly rewritten DHT code

=item * BEP 9: Extension for Peers to Send Metadata Files

=item * ut_pex ...despite it being undocumented

=item * resume API version numbers

=back

=head1 Short term goals

=over

=item * DHT callbacks (?)

=item * Fast Ext (Fast set)

=item * Public quick resume interface

=item * Make trackers keep track of their own complete/incomplete tally
rather than stuffing their value in the parent tier.

=back

=head1 Long term goals

=over

=item * Net::BitTorrent::Notes

=item * Complete test suite

Create a series of bad .torrent files to test N::B::Torrent with:

=over

=item * invalid pieces string

=over

=item * string length does not % 40 evenly

=item * string is shorter than 40 chars

=item * (piece_length * num_pieces) != total_size_of_torrent

=back

=back

=item * Per-torrent transfer limits.

=item * improve file handling

=over

=item * large torrents (> 4G) typically require 64bit math

=item * intermediate .piece file to store incoming blocks

=back

=item * scripts/wx-gui-client.pl (perhaps)

=item * PoCo::BitTorrent

=item * Proxy support

=item * uTP depending on how well it works out if/when it hits IETF

=back

=head1 Duke Nukem: Forever

=over

=item * Wire protocol encryption
<http://www.azureuswiki.com/index.php/Message_Stream_Encryption#Implementation_Notes_for_BitTorrent_Clients>

=back

=head1 Author

Sanko Robinson <sanko@cpan.org> - http://sankorobinson.com/

CPAN ID: SANKO

=head1 License and Legal

Copyright (C) 2008 by Sanko Robinson E<lt>sanko@cpan.orgE<gt>

This program is free software; you can redistribute it and/or modify
it under the terms of The Artistic License 2.0.  See the F<LICENSE>
file included with this distribution or
http://www.perlfoundation.org/artistic_license_2_0.  For
clarification, see http://www.perlfoundation.org/artistic_2_0_notes.

When separated from the distribution, all POD documentation is covered
by the Creative Commons Attribution-Share Alike 3.0 License.  See
http://creativecommons.org/licenses/by-sa/3.0/us/legalcode.  For
clarification, see http://creativecommons.org/licenses/by-sa/3.0/us/.

Neither this module nor the L<Author|/Author> is affiliated with
BitTorrent, Inc.

=for svn $Id$

=cut
